$path = "c:\Users\belac_odysseus\Documents\Projetos\consultor_financeiro\dados_goias\csv_tables"
Set-Location $path

$renames = @{
	"tabela80.csv" = "80-participacao-pib-goias-cenario-nacional.csv"
	"tabela81.csv" = "81-variacao-anual-pib-goiano.csv"
	"tabela82.csv" = "82-crescimento-trimestral-pib-goias-brasil.csv"
	"tabela83.csv" = "83-ranking-pib-unidade-federacao.csv"
	"tabela84.csv" = "84-variacao-inpc-capitais-brasileiras.csv"
	"tabela85.csv" = "85-variacao-ipca-capitais-brasileiras.csv"
	"tabela86.csv" = "86-area-plantio-goias-produto-agricola.csv"
	"tabela87.csv" = "87-area-colhida-goias-produto-agricola.csv"
	"tabela88.csv" = "88-producao-agricola-goias-produto.csv"
	"tabela89.csv" = "89-produtividade-agricola-goias-produto.csv"
	"tabela90.csv" = "90-producao-graos-goias-centro-oeste-brasil.csv"
	"tabela91.csv" = "91-producao-principais-produtos-agricolas-goias.csv"
	"tabela92.csv" = "92-producao-principais-produtos-agricolas-centro-oeste.csv"
	"tabela93.csv" = "93-producao-principais-produtos-agricolas-brasil.csv"
	"tabela94.csv" = "94-presenca-goiana-comercializacao-ceasa-go.csv"
	"tabela95.csv" = "95-municipios-lideres-oferta-ceasa-go.csv"
	"tabela96.csv" = "96-produtos-mais-comercializados-ceasa-go.csv"
	"tabela97.csv" = "97-extracao-vegetal-silvicultura-goias.csv"
	"tabela98.csv" = "98-rebanhos-producao-leite-goias-centro-oeste-brasil.csv"
	"tabela99.csv" = "99-efetivo-rebanhos-goias.csv"
	"tabela100.csv" = "100-producao-mel-la-ovos-rebanho-avicola-goias.csv"
	"tabela101.csv" = "101-abate-animais-goias.csv"
	"tabela102.csv" = "102-empresas-ativas-brasil-uf.csv"
	"tabela103.csv" = "103-setores-destaque-empresas-goias.csv"
	"tabela104.csv" = "104-servicos-nao-financeiros-goias.csv"
	"tabela105.csv" = "105-empresas-pessoal-ocupado-goias-municipios.csv"
	"tabela106.csv" = "106-indicadores-comercio-goias-brasil.csv"
	"tabela107.csv" = "107-receita-margem-comercializacao-goias-brasil.csv"
	"tabela108.csv" = "108-agencias-bancarias-goias.csv"
	"tabela109.csv" = "109-crescimento-producao-industrial-goias.csv"
	"tabela110.csv" = "110-industria-goias-unidades-pessoal.csv"
	"tabela111.csv" = "111-usinas-etanol-filiadas-sifaeg-goias.csv"
	"tabela112.csv" = "112-balanca-comercial-goias-brasil.csv"
	"tabela113.csv" = "113-produtos-lideres-exportacao-goias.csv"
	"tabela114.csv" = "114-produtos-mais-importados-goias.csv"
	"tabela115.csv" = "115-destinos-exportacoes-goias.csv"
	"tabela116.csv" = "116-origem-importacoes-goias.csv"
	"tabela117.csv" = "117-maiores-compradores-produtos-goianos.csv"
	"tabela118.csv" = "118-principais-fornecedores-goias.csv"
	"tabela119.csv" = "119-ranking-exportacao-uf.csv"
	"tabela120.csv" = "120-ranking-importacao-uf.csv"
	"tabela121.csv" = "121-municipios-goianos-maior-volume-exportacao.csv"
	"tabela122.csv" = "122-destinos-finais-produtos-goianos.csv"
	"tabela123.csv" = "123-arrecadacao-impostos-federais-goias.csv"
	"tabela124.csv" = "124-arrecadacao-icms-goias-setor.csv"
	"tabela125.csv" = "125-receita-bruta-estado-goias.csv"
	"tabela126.csv" = "126-gastos-governo-goias-funcao-categoria.csv"
	"tabela127.csv" = "127-evolucao-arrecadacao-goias.csv"
	"tabela128.csv" = "128-despesas-governo-goias-execucao-previsao.csv"
	"tabela129.csv" = "129-financiamentos-fco-goias-centro-oeste.csv"
	"grafico22.csv" = "grafico22-producao-acucar-goias.csv"
	"grafico23.csv" = "grafico23-producao-etanol-goias.csv"
}

foreach ($oldName in $renames.Keys) {
	if (Test-Path $oldName) {
		Rename-Item -Path $oldName -NewName $renames[$oldName]
	}
}