analise_macro:
  description: > 
    Analise o cenário atual do mercado financeiro global, considerando:

    1. Principais setores (Tecnologia, Financeiro, Saúde, Energia, Consumo, Industrial, Materiais, Utilidades, Imobiliário, Iíndices, Moedas, Criptomoedas, ETFs e Commodities)
    2. Média móvel dos setores
    3. Volatilidade dos setores
    4. Retornos dos setores
    5. Correlações entre setores
  expected_output: >
    Relatório detalhado sobre o cenário atual do mercado financeiro, os 3 melhores setores para investir seja comprado ou vendido e suas tendências.
    Estratégias de investimento para os 3 melhores setores.

pesquisa_ativos:
  description: >
    Sua tarefa é realizar uma pesquisa aprofundada sobre os ativos mais promissores para compor um portfólio de investimentos.
    Para isso, utilize fontes confiáveis de dados financeiros e econômicos, analisando fatores como:

    - Ciclos econômicos e tendências globais
    - Políticas monetárias e fiscais
    - Setores com maior potencial de crescimento e estabilidade
    - Correlação entre setores e classes de ativos

    Você terá acesso a um relatório detalhado sobre o cenário macroeconômico atual, que identificará os **três setores mais promissores para investir**.
    Sua pesquisa deve focar nesses setores para encontrar **os ativos individuais mais adequados**.

    Utilize ferramentas de busca para encontrar relatórios, notícias e análises de mercado que auxiliem na escolha dos ativos.

  expected_output: >
    Um relatório contendo:
    - Uma lista de **ativos recomendados** com base na pesquisa (ações, ETFs, commodities, criptomoedas, etc.).
    - Justificativa para a escolha de cada ativo, com base em tendências macroeconômicas e análises de mercado.
    - Fontes utilizadas na pesquisa.

otimizacao_portfolio:
  description: >
    Agora que temos uma lista de ativos promissores baseada na pesquisa anterior, sua tarefa é otimizar o portfólio, garantindo uma alocação equilibrada e eficiente.

    Utilize modelos quantitativos para calcular a melhor distribuição de capital entre os ativos selecionados, considerando:

    - Retornos esperados e volatilidade
    - Correlação entre ativos
    - Estratégias de balanceamento (exemplo: Hierarchical Risk Parity)

    Sua análise deve incluir sugestões de **percentual de alocação** para cada ativo e estratégias para rebalanceamento periódico.

  expected_output: >
    Um relatório estruturado contendo:
    - A composição do portfólio otimizado.
    - Percentual de capital a ser investido em cada ativo.
    - Justificativa técnica e quantitativa para cada alocação.
    - Estratégia de rebalanceamento e ajustes futuros.



estrategia_long_short:
  description: >
    Com base no relatório detalhado do portfólio construído anteriormente, sua tarefa é desenvolver uma estratégia de long & short para os ativos selecionados.

    Para isso, utilize estatísticas e indicadores técnicos de cada ativo, garantindo que as posições compradas (long) estejam em ativos subvalorizados com forte potencial de valorização e as posições vendidas (short) estejam em ativos supervalorizados ou com tendência de queda.

    A estratégia deve levar em consideração:
    - Indicadores técnicos como médias móveis, RSI, MACD e bandas de Bollinger.
    - Correlação entre os ativos do portfólio e sua sensibilidade ao mercado.
    - Riscos associados e estratégias de hedge para minimizar potenciais perdas.
    - Critérios claros para entrada e saída das operações.

    Você terá acesso a uma ferramenta que fornecerá estatísticas e indicadores técnicos de cada ativo do portfólio, permitindo uma análise detalhada para a tomada de decisão.

  expected_output: >
    Um relatório estruturado contendo:

    - Os ativos do portfólio.
    - A porcentagem de capital que deve ser investido em cada ativo.
    - Uma visão geral da estratégia long & short e seus objetivos.
    - A lista de ativos do portfólio classificados em posições long e short.
    - A justificativa técnica e estatística para cada posição.
    - Os critérios de entrada e saída das operações.
    - Um resumo estratégico incluindo potenciais riscos e estratégias de hedge.

relatorio_final:
  description: >
    Sua tarefa é consolidar todas as análises realizadas nas tasks anteriores e produzir um relatório final detalhado.

    O relatório deve conter:
    - A lista definitiva de ativos que irão compor o portfólio, com percentuais de alocação de capital.
    - A estratégia a ser utilizada para cada ativo, incluindo pontos de entrada, saída e duração esperada da operação.
    - Uma análise de riscos e retornos esperados, com base nas informações extraídas das tasks anteriores.
    - Explicação clara sobre a lógica por trás das decisões estratégicas, conectando a análise macroeconômica com a construção do portfólio e as estratégias de long & short.
    - Fatores adicionais relevantes identificados ao longo do processo, como impactos de eventos macroeconômicos e variações setoriais.

  expected_output: >
    Um relatório estruturado em formato Markdown contendo:

    - Uma introdução resumindo as principais decisões do portfólio.
    - A composição detalhada do portfólio final, incluindo percentuais de capital alocados em cada ativo.
    - Estratégias operacionais, com justificativas baseadas nos preços de entrada, saída e tempo estimado da operação.
    - Riscos e retornos esperados, com base nas análises macroeconômicas e técnicas realizadas anteriormente.
    - Considerações finais sobre o portfólio e possíveis ajustes futuros, levando em conta variações de mercado.

